name: foodibizz
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  device_preview: ^1.1.0
  dio: ^5.3.3
  dio_smart_retry: ^6.0.0
  dotted_border: ^2.1.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.1.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.6
  flutter_slidable: ^3.0.1
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  multiple_result: ^5.1.0
  path_provider: ^2.1.1
  pdf: ^3.10.7
  printing: ^5.11.1
  responsive_framework: ^1.1.1
  talker_dio_logger: ^2.3.1
  talker_flutter: ^3.5.4
  flutter_displaymode: ^0.6.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  riverpod_lint: ^2.3.4
  riverpod_test: ^0.1.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    # - lib/src/.env.staging
    # - lib/src/.env.production
    # - lib/src/.env.development
